"use client";

import React, { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

import {
  Zap, ArrowRight, Star, TrendingUp, DollarSign, Target,
  Clock, BarChart3, Users, CheckCircle2, Sparkles, BookOpen,
  Shield, ChevronRight, Quote, Rocket, Calculator,
} from "lucide-react";
import { getTopHustles } from "@/data/side-hustles";
import { formatCurrency, getDifficultyColor } from "@/lib/utils";
import { PRICING_PLANS } from "@/lib/stripe";

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, delay: i * 0.1 },
  }),
};

const stats = [
  { label: "Side Hustles", value: "100+", icon: Sparkles },
  { label: "Active Users", value: "25K+", icon: Users },
  { label: "Income Tracked", value: "$2.4M+", icon: DollarSign },
  { label: "Success Rate", value: "89%", icon: TrendingUp },
];

const features = [
  {
    icon: Zap,
    title: "AI Discovery Quiz",
    description: "Answer 10 questions and our AI matches you with the perfect side hustles based on your skills, time, and goals.",
    color: "bg-primary-100 text-primary",
  },
  {
    icon: BookOpen,
    title: "Personalized Playbooks",
    description: "Get a custom 30-day action plan generated by GPT-4 for your chosen side hustle. Step-by-step, no guesswork.",
    color: "bg-secondary-100 text-secondary",
  },
  {
    icon: BarChart3,
    title: "Income Tracker",
    description: "Log every dollar earned, visualize your growth with charts, earn badges, and build income streaks.",
    color: "bg-accent-100 text-accent-700",
  },
  {
    icon: Target,
    title: "100+ Side Hustles",
    description: "Detailed profiles for every hustle including income ranges, startup costs, pros/cons, and step-by-step launch plans.",
    color: "bg-purple-100 text-purple-600",
  },
  {
    icon: Users,
    title: "Community & Forums",
    description: "Connect with fellow hustlers, share success stories, join challenges, and get accountability partners.",
    color: "bg-pink-100 text-pink-600",
  },
  {
    icon: Shield,
    title: "Tool Marketplace",
    description: "Curated recommendations for the best tools, software, and resources for each side hustle.",
    color: "bg-blue-100 text-blue-600",
  },
];

const testimonials = [
  {
    name: "Sarah K.",
    role: "Freelance Writer",
    avatar: "SK",
    content: "SideHustle.ai matched me with freelance writing and gave me a 30-day plan. I went from zero to $2,400/month in just 8 weeks. The AI playbook was a game-changer.",
    income: "$2,400/mo",
    hustle: "Freelance Writing",
  },
  {
    name: "Marcus J.",
    role: "Print on Demand Seller",
    avatar: "MJ",
    content: "I was skeptical about the quiz, but it nailed it. Print on demand was perfect for my design skills and limited time. Now I earn passive income from 300+ designs on Etsy.",
    income: "$1,800/mo",
    hustle: "Print on Demand",
  },
  {
    name: "Priya R.",
    role: "AI Automation Consultant",
    avatar: "PR",
    content: "The AI automation services hustle was exactly what I needed. With my tech background and the playbook's guidance, I landed my first $5K client within 3 weeks.",
    income: "$8,500/mo",
    hustle: "AI Automation",
  },
];

const howItWorks = [
  {
    step: "01",
    title: "Take the AI Quiz",
    description: "Answer 10 quick questions about your skills, time, budget, and goals. Takes just 2 minutes.",
    icon: Zap,
  },
  {
    step: "02",
    title: "Get Matched",
    description: "Our AI analyzes your answers and matches you with the best side hustles from our database of 100+.",
    icon: Target,
  },
  {
    step: "03",
    title: "Follow Your Playbook",
    description: "Get a personalized 30-day action plan with daily tasks, resources, and milestones.",
    icon: BookOpen,
  },
  {
    step: "04",
    title: "Track & Grow",
    description: "Log your income, track your progress, earn badges, and scale with our tools and community.",
    icon: TrendingUp,
  },
];

// ── Income Calculator Data ───────────────────────────────────────
interface IncomeData {
  label: string;
  beginner: { min: number; max: number };
  intermediate: { min: number; max: number };
  expert: { min: number; max: number };
  sampleSize: number;
}

const incomeDataByHustle: Record<string, IncomeData> = {
  "freelance-writing": {
    label: "Freelance Writing",
    beginner: { min: 15, max: 30 },
    intermediate: { min: 35, max: 75 },
    expert: { min: 80, max: 150 },
    sampleSize: 4200,
  },
  "web-development": {
    label: "Web Development",
    beginner: { min: 25, max: 50 },
    intermediate: { min: 60, max: 120 },
    expert: { min: 125, max: 250 },
    sampleSize: 3800,
  },
  "print-on-demand": {
    label: "Print on Demand",
    beginner: { min: 5, max: 15 },
    intermediate: { min: 18, max: 40 },
    expert: { min: 45, max: 100 },
    sampleSize: 2900,
  },
  youtube: {
    label: "YouTube",
    beginner: { min: 3, max: 10 },
    intermediate: { min: 15, max: 50 },
    expert: { min: 60, max: 200 },
    sampleSize: 3100,
  },
  "ai-automation": {
    label: "AI Automation",
    beginner: { min: 30, max: 60 },
    intermediate: { min: 75, max: 150 },
    expert: { min: 160, max: 300 },
    sampleSize: 1800,
  },
  "online-courses": {
    label: "Online Courses",
    beginner: { min: 8, max: 20 },
    intermediate: { min: 25, max: 65 },
    expert: { min: 70, max: 180 },
    sampleSize: 2400,
  },
  dropshipping: {
    label: "Dropshipping",
    beginner: { min: 5, max: 18 },
    intermediate: { min: 22, max: 55 },
    expert: { min: 60, max: 140 },
    sampleSize: 3500,
  },
  "social-media": {
    label: "Social Media Management",
    beginner: { min: 15, max: 30 },
    intermediate: { min: 35, max: 70 },
    expert: { min: 75, max: 150 },
    sampleSize: 2700,
  },
};

const hustleOptions = Object.entries(incomeDataByHustle).map(([key, val]) => ({
  value: key,
  label: val.label,
}));

type ExperienceLevel = "beginner" | "intermediate" | "expert";

function IncomeCalculator() {
  const [selectedHustle, setSelectedHustle] = useState("freelance-writing");
  const [hoursPerWeek, setHoursPerWeek] = useState(10);
  const [experience, setExperience] = useState<ExperienceLevel>("beginner");

  const hustleData = incomeDataByHustle[selectedHustle];
  const rate = hustleData[experience];

  const monthlyMin = Math.round(rate.min * hoursPerWeek * 4.33);
  const monthlyMax = Math.round(rate.max * hoursPerWeek * 4.33);
  const annualMin = monthlyMin * 12;
  const annualMax = monthlyMax * 12;

  // Bar fill percentage relative to a max of ~$20k/mo
  const barPercent = Math.min((monthlyMax / 20000) * 100, 100);

  return (
    <section className="py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <Badge variant="outline" className="mb-4">
            <Calculator className="w-3 h-3 mr-1.5" />
            Income Calculator
          </Badge>
          <h2 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-4">
            How Much Could <span className="text-primary">You Earn?</span>
          </h2>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Estimate your potential side hustle income based on the type of work, hours, and your experience level.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <Card className="border-2">
            <CardContent className="p-6 sm:p-8">
              <div className="grid md:grid-cols-2 gap-8">
                {/* Controls */}
                <div className="space-y-6">
                  {/* Hustle Type */}
                  <div>
                    <label className="block text-sm font-semibold text-foreground mb-2">
                      Select Hustle Type
                    </label>
                    <select
                      value={selectedHustle}
                      onChange={(e) => setSelectedHustle(e.target.value)}
                      className="w-full h-10 px-3 rounded-lg border border-border bg-white text-sm font-medium text-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
                    >
                      {hustleOptions.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Hours per week */}
                  <div>
                    <label className="block text-sm font-semibold text-foreground mb-2">
                      Hours per Week: <span className="text-primary">{hoursPerWeek}h</span>
                    </label>
                    <input
                      type="range"
                      min={1}
                      max={40}
                      value={hoursPerWeek}
                      onChange={(e) => setHoursPerWeek(Number(e.target.value))}
                      className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-primary"
                    />
                    <div className="flex justify-between text-xs text-muted-foreground mt-1">
                      <span>1h</span>
                      <span>10h</span>
                      <span>20h</span>
                      <span>30h</span>
                      <span>40h</span>
                    </div>
                  </div>

                  {/* Experience level */}
                  <div>
                    <label className="block text-sm font-semibold text-foreground mb-2">
                      Experience Level
                    </label>
                    <div className="flex gap-2">
                      {(["beginner", "intermediate", "expert"] as ExperienceLevel[]).map((level) => (
                        <button
                          key={level}
                          onClick={() => setExperience(level)}
                          className={`flex-1 py-2.5 px-3 rounded-lg text-sm font-medium transition-all duration-200 border-2 ${
                            experience === level
                              ? "bg-primary text-white border-primary shadow-sm"
                              : "bg-white text-gray-600 border-border hover:border-primary/30"
                          }`}
                        >
                          {level.charAt(0).toUpperCase() + level.slice(1)}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Output */}
                <div className="flex flex-col justify-center">
                  <div className="bg-gradient-to-br from-primary-50 to-secondary-50 rounded-2xl p-6 border border-primary-100">
                    {/* Monthly */}
                    <div className="mb-4">
                      <div className="text-sm text-gray-500 mb-1">Estimated Monthly Income</div>
                      <div className="font-heading text-3xl sm:text-4xl font-extrabold text-foreground">
                        {formatCurrency(monthlyMin)} - {formatCurrency(monthlyMax)}
                      </div>
                    </div>

                    {/* Annual */}
                    <div className="mb-5">
                      <div className="text-sm text-gray-500 mb-1">Estimated Annual Income</div>
                      <div className="font-heading text-xl font-bold text-primary">
                        {formatCurrency(annualMin)} - {formatCurrency(annualMax)}
                      </div>
                    </div>

                    {/* Visual bar */}
                    <div className="mb-4">
                      <div className="flex items-center justify-between text-xs text-muted-foreground mb-1.5">
                        <span>Earning Potential</span>
                        <span>{Math.round(barPercent)}%</span>
                      </div>
                      <div className="h-3 bg-white rounded-full overflow-hidden border border-primary-100">
                        <motion.div
                          className="h-full bg-gradient-to-r from-primary to-secondary rounded-full"
                          initial={{ width: 0 }}
                          animate={{ width: `${barPercent}%` }}
                          transition={{ duration: 0.6, ease: "easeOut" }}
                          key={`${selectedHustle}-${hoursPerWeek}-${experience}`}
                        />
                      </div>
                    </div>

                    {/* Credibility note */}
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <Users className="w-3.5 h-3.5" />
                      <span>
                        Based on data from{" "}
                        <span className="font-semibold text-foreground">
                          {hustleData.sampleSize.toLocaleString()}
                        </span>{" "}
                        side hustlers
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}

export default function HomePage() {
  const topHustles = getTopHustles(6);


  return (
    <div className="overflow-hidden">
      {/* Hero Section */}
      <section className="relative bg-hero-pattern">
        <div className="absolute inset-0 bg-gradient-to-b from-primary-50/50 to-transparent" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-24 sm:pt-24 sm:pb-32">
          <div className="max-w-4xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <Badge className="mb-6 px-4 py-1.5 text-sm bg-primary-100 text-primary border-primary-200">
                <Sparkles className="w-3.5 h-3.5 mr-1.5" />
                Powered by AI — Trusted by 25,000+ hustlers
              </Badge>
            </motion.div>

            <motion.h1
              className="font-heading text-4xl sm:text-5xl lg:text-6xl font-extrabold text-foreground leading-tight mb-6"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
            >
              Discover Your Perfect{" "}
              <span className="text-gradient">Side Hustle</span>{" "}
              in 2 Minutes
            </motion.h1>

            <motion.p
              className="text-lg sm:text-xl text-gray-600 mb-8 max-w-2xl mx-auto leading-relaxed"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              Take our AI-powered quiz to find the side hustle that matches your skills, schedule, and income goals. Then get a personalized 30-day playbook to launch it.
            </motion.p>

            <motion.div
              className="flex flex-col sm:flex-row items-center justify-center gap-4"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
            >
              <Link href="/quiz">
                <Button size="xl" className="gap-2 text-base shadow-lg shadow-primary/25 hover:shadow-xl hover:shadow-primary/30">
                  <Zap className="w-5 h-5" />
                  Take the Free Quiz
                  <ArrowRight className="w-5 h-5" />
                </Button>
              </Link>
              <Link href="/hustles">
                <Button variant="outline" size="xl" className="gap-2 text-base">
                  <BookOpen className="w-5 h-5" />
                  Browse Side Hustles
                </Button>
              </Link>
            </motion.div>

            <motion.div
              className="flex items-center justify-center gap-6 mt-8 text-sm text-gray-500"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.5 }}
            >
              <div className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-primary" />
                <span>100% Free Quiz</span>
              </div>
              <div className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-primary" />
                <span>No Credit Card</span>
              </div>
              <div className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-primary" />
                <span>Instant Results</span>
              </div>
            </motion.div>
          </div>

          {/* Stats Bar */}
          <motion.div
            className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-16 max-w-3xl mx-auto"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
          >
            {stats.map((stat) => (
              <div key={stat.label} className="text-center p-4 bg-white rounded-xl shadow-sm border border-border">
                <stat.icon className="w-5 h-5 text-primary mx-auto mb-2" />
                <div className="font-heading text-2xl font-bold text-foreground">{stat.value}</div>
                <div className="text-xs text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4">How It Works</Badge>
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-4">
              From Zero to Earning in <span className="text-primary">4 Simple Steps</span>
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Our AI-powered platform makes it ridiculously easy to find, launch, and grow a profitable side hustle.
            </p>
          </div>

          <div className="grid md:grid-cols-4 gap-8">
            {howItWorks.map((item, i) => (
              <motion.div
                key={item.step}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-50px" }}
                variants={fadeUp}
                className="relative"
              >
                {i < 3 && (
                  <div className="hidden md:block absolute top-10 left-[60%] w-[80%] h-[2px] bg-gradient-to-r from-primary/30 to-primary/10" />
                )}
                <div className="text-center">
                  <div className="w-20 h-20 bg-white rounded-2xl shadow-md border border-border flex items-center justify-center mx-auto mb-4 relative">
                    <item.icon className="w-8 h-8 text-primary" />
                    <span className="absolute -top-2 -right-2 w-7 h-7 bg-primary text-white rounded-full flex items-center justify-center text-xs font-bold">
                      {item.step}
                    </span>
                  </div>
                  <h3 className="font-heading text-lg font-bold mb-2">{item.title}</h3>
                  <p className="text-sm text-gray-600">{item.description}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Top Side Hustles */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-12 gap-4">
            <div>
              <Badge variant="outline" className="mb-3">Trending Side Hustles</Badge>
              <h2 className="font-heading text-3xl sm:text-4xl font-bold text-foreground">
                Popular Side Hustles <span className="text-primary">Right Now</span>
              </h2>
            </div>
            <Link href="/hustles">
              <Button variant="outline" className="gap-1.5">
                View All Hustles
                <ArrowRight className="w-4 h-4" />
              </Button>
            </Link>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {topHustles.map((hustle, i) => (
              <motion.div
                key={hustle.id}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-30px" }}
                variants={fadeUp}
              >
                <Link href={`/hustles/${hustle.slug}`}>
                  <Card className="group hover:shadow-lg hover:border-primary/20 transition-all duration-300 h-full">
                    <CardContent className="p-6">
                      <div className="flex items-start justify-between mb-4">
                        <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center group-hover:bg-primary-200 transition-colors">
                          <DollarSign className="w-6 h-6 text-primary" />
                        </div>
                        <div className="flex items-center gap-2">
                          {hustle.is_trending && (
                            <Badge variant="accent" className="text-xs">
                              <TrendingUp className="w-3 h-3 mr-1" />
                              Trending
                            </Badge>
                          )}
                        </div>
                      </div>

                      <h3 className="font-heading text-lg font-bold mb-1 group-hover:text-primary transition-colors">
                        {hustle.name}
                      </h3>
                      <p className="text-sm text-muted-foreground mb-4">{hustle.tagline}</p>

                      <div className="space-y-2.5 mb-4">
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-gray-500 flex items-center gap-1.5">
                            <DollarSign className="w-3.5 h-3.5" />
                            Income Range
                          </span>
                          <span className="font-semibold text-primary">
                            {formatCurrency(hustle.income_range_min)} - {formatCurrency(hustle.income_range_max)}/mo
                          </span>
                        </div>
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-gray-500 flex items-center gap-1.5">
                            <Clock className="w-3.5 h-3.5" />
                            Time to Income
                          </span>
                          <span className="font-medium">{hustle.time_to_first_income}</span>
                        </div>
                        <div className="flex items-center justify-between text-sm">
                          <span className="text-gray-500 flex items-center gap-1.5">
                            <Target className="w-3.5 h-3.5" />
                            Startup Cost
                          </span>
                          <span className="font-medium">
                            {hustle.startup_cost_min === 0 ? "Free" : formatCurrency(hustle.startup_cost_min)} - {formatCurrency(hustle.startup_cost_max)}
                          </span>
                        </div>
                      </div>

                      <div className="flex items-center justify-between pt-3 border-t border-border">
                        <Badge className={`${getDifficultyColor(hustle.difficulty).bg} ${getDifficultyColor(hustle.difficulty).text} border-0`}>
                          {getDifficultyColor(hustle.difficulty).label}
                        </Badge>
                        <span className="text-sm text-primary font-medium flex items-center gap-1 group-hover:gap-2 transition-all">
                          Learn More <ChevronRight className="w-4 h-4" />
                        </span>
                      </div>
                    </CardContent>
                  </Card>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4">Platform Features</Badge>
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-4">
              Everything You Need to <span className="text-primary">Launch & Grow</span>
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              From discovery to income tracking, we have built every tool you need to build a successful side hustle.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <motion.div
                key={feature.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-30px" }}
                variants={fadeUp}
              >
                <Card className="h-full hover:shadow-md transition-shadow">
                  <CardContent className="p-6">
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${feature.color}`}>
                      <feature.icon className="w-6 h-6" />
                    </div>
                    <h3 className="font-heading text-lg font-bold mb-2">{feature.title}</h3>
                    <p className="text-sm text-gray-600 leading-relaxed">{feature.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4">
              <Star className="w-3 h-3 mr-1 fill-accent text-accent" />
              Success Stories
            </Badge>
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-4">
              Real People, <span className="text-primary">Real Income</span>
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Thousands of hustlers have used SideHustle.ai to discover and launch profitable side hustles.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, i) => (
              <motion.div
                key={testimonial.name}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-30px" }}
                variants={fadeUp}
              >
                <Card className="h-full">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-1 mb-4">
                      {[...Array(5)].map((_, j) => (
                        <Star key={j} className="w-4 h-4 fill-accent text-accent" />
                      ))}
                    </div>
                    <Quote className="w-8 h-8 text-primary/20 mb-2" />
                    <p className="text-gray-600 mb-6 leading-relaxed">{testimonial.content}</p>
                    <div className="flex items-center justify-between pt-4 border-t border-border">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-primary-100 rounded-full flex items-center justify-center">
                          <span className="text-sm font-bold text-primary">{testimonial.avatar}</span>
                        </div>
                        <div>
                          <div className="font-semibold text-sm">{testimonial.name}</div>
                          <div className="text-xs text-muted-foreground">{testimonial.hustle}</div>
                        </div>
                      </div>
                      <Badge variant="success" className="font-bold">
                        {testimonial.income}
                      </Badge>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Income Calculator */}
      <IncomeCalculator />

      {/* Pricing Preview */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4">Pricing</Badge>
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-4">
              Start Free, <span className="text-primary">Upgrade When Ready</span>
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Our free plan gives you everything you need to get started. Upgrade to Pro for unlimited AI playbooks and advanced tracking.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {PRICING_PLANS.map((plan, i) => (
              <motion.div
                key={plan.id}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-30px" }}
                variants={fadeUp}
              >
                <Card className={`h-full relative ${plan.highlighted ? "border-primary shadow-lg scale-105 z-10" : ""}`}>
                  {plan.highlighted && (
                    <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                      <Badge className="bg-primary text-white shadow-sm">Most Popular</Badge>
                    </div>
                  )}
                  <CardContent className="p-6">
                    <h3 className="font-heading text-xl font-bold mb-1">{plan.name}</h3>
                    <div className="flex items-baseline gap-1 mb-1">
                      <span className="font-heading text-4xl font-extrabold">
                        ${plan.price}
                      </span>
                      {plan.billing_period && (
                        <span className="text-muted-foreground">/{plan.billing_period}</span>
                      )}
                      {plan.tier === "lifetime" && (
                        <span className="text-muted-foreground text-sm">one-time</span>
                      )}
                    </div>
                    {plan.tier === "free" && (
                      <p className="text-sm text-muted-foreground mb-4">Free forever</p>
                    )}
                    {plan.tier === "pro" && (
                      <p className="text-sm text-muted-foreground mb-4">7-day free trial</p>
                    )}
                    {plan.tier === "lifetime" && (
                      <p className="text-sm text-muted-foreground mb-4">Pay once, own forever</p>
                    )}

                    <Link href={plan.tier === "free" ? "/signup" : "/pricing"}>
                      <Button
                        className="w-full mb-6"
                        variant={plan.highlighted ? "default" : "outline"}
                      >
                        {plan.cta}
                      </Button>
                    </Link>

                    <ul className="space-y-2.5">
                      {plan.features.map((feature) => (
                        <li key={feature} className="flex items-start gap-2 text-sm">
                          <CheckCircle2 className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                          <span className="text-gray-600">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="relative bg-gradient-to-br from-primary to-secondary rounded-3xl p-8 sm:p-16 text-center text-white overflow-hidden">
            <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2240%22%20height%3D%2240%22%20viewBox%3D%220%200%2040%2040%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M0%2040L40%200H20L0%2020M40%2040V20L20%2040%22%20fill%3D%22rgba(255%2C255%2C255%2C0.03)%22%20%2F%3E%3C%2Fsvg%3E')] opacity-50" />
            <div className="relative z-10">
              <Rocket className="w-12 h-12 mx-auto mb-6 text-white/80" />
              <h2 className="font-heading text-3xl sm:text-4xl lg:text-5xl font-extrabold mb-4">
                Ready to Start Your Side Hustle Journey?
              </h2>
              <p className="text-lg text-white/80 max-w-2xl mx-auto mb-8">
                Join 25,000+ people who have discovered their perfect side hustle with our AI-powered platform. Your future income stream is just a quiz away.
              </p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link href="/quiz">
                  <Button size="xl" variant="white" className="gap-2 text-primary font-bold">
                    <Zap className="w-5 h-5" />
                    Take the Free Quiz Now
                    <ArrowRight className="w-5 h-5" />
                  </Button>
                </Link>
              </div>
              <div className="flex items-center justify-center gap-4 mt-6 text-sm text-white/60">
                <div className="flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" />
                  Takes 2 minutes
                </div>
                <div className="flex items-center gap-1">
                  <Shield className="w-3.5 h-3.5" />
                  No account needed
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
